/**
 * The AST of Quickfall.
 */

#ifndef AST_H
#define AST_H

typedef enum {

    AST_TYPE_ROOT,
    AST_TYPE_FUNC_ROOT,

    AST_TYPE_FUNCTION_DECLARATION,
    AST_TYPE_ASM_FUNCTION_DECLARATION,

    AST_TYPE_VARIABLE_DECLARATION,
    AST_TYPE_VARIABLE_MODIFICATION,
    AST_TYPE_VALUE

} AST_TYPE;

#endif