#ifndef TOKENS_H
#define TOKENS_H

enum TokenType {
    ASM_FUNCTION,
    FUNCTION,
    RETURN,
    VAR,
    BRACKETS_OPEN,
    BRACKETS_CLOSE,
    PAREN_OPEN,
    PAREN_CLOSE,
    ARRAY_OPEN,
    ARRAY_CLOSE,
    NUMBER,
    STRING,
    BOOLEAN_VALUE,
    NU,
    KEYWORD,
    SEMICOLON,
    COMMA,
    DECLARE,
    USE,
    NONE,
    MATH_OP
};

/**
 * An lexer token generated by the Lexer.
 */
struct Token {
	enum TokenType type;
	char* value;
};


#endif
